
trigger:
- master

variables:

  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'desattiracr'
  imageRepository: 'gosample'
  containerRegistry: 'desattiracr.azurecr.io'
  dockerfilePath: '**/Dockerfile'
  tag: '$(Build.BuildId)'
  imagePullSecret: 'desattiracr-auth'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'
  
  azureServiceConnection: 'rmdev'
  k8sNamespaceForPR: '$(System.pullRequest.sourceBranch)'
  k8sNamespace: 'default'
  AZDSControllerName: 'desattir-bg'
  AZDSControllerRG: 'desattir-bg'

stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: echo "hello world" 


- stage: DeployPR
  displayName: Deploy PR review app
  dependsOn: Build
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/pull/'))
  jobs:
  - deployment: Deploy
    displayName: Deploy job
    pool:
      vmImage: 'windows-latest'
      
    environment: 'desattiraks-bg.default'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureCLI@1
            displayName: 'List all review app URLs'
            inputs:
              azureSubscription: $(azureServiceConnection)
              scriptLocation: inlineScript
              inlineScript: |
                az aks use-dev-spaces -n $(AZDSControllerName) -g $(AZDSControllerRG) -y -s $(k8sNamespace)/$(k8sNamespaceForPR)
                azds prep
                dir
                azds up
                azds list-uris
